import type { Topic } from "./topics";
import { dailyTopics20260823 } from "./daily-topics-2026-08-23";

type Category = "女性成長" | "金錢價值觀" | "親子關係";
type Draft = Pick<Topic, "category" | "title" | "hook" | "scene" | "empathy" | "explain" | "action" | "reframe" | "singleCta" | "contentType">;

const formulaConfig = dailyTopics20260823.slice(0, 8).map(({ formula, formulaOrder }) => ({ formula, formulaOrder }));
const guardrails: Record<Category, Pick<Topic, "risk" | "check">> = {
  女性成長: { risk: "只談職涯與事業發展，不延伸到感情、外貌或泛自我成長。", check: "確認內容聚焦職場界線、談薪升遷、轉職、定位、創業、協作、領導或工作自信。" },
  金錢價值觀: { risk: "不提供投資、借貸、金融商品或報酬保證建議。", check: "確認內容只談日常選擇、情緒與金錢價值觀，不引導任何金融行動。" },
  親子關係: { risk: "不替孩子貼標籤，不承諾孩子會因此改變。", check: "確認內容以照顧者可選擇的回應為主，保留孩子當下的感受與差異。" },
};

const drafts: Draft[] = [
  { category: "女性成長", title: "同事又來問幫忙時，先把可支援的時段說出來", hook: "同事一說這個你最會，你是不是又把自己的工作往後排了？", scene: "下午四點，對方帶著一份急件站在你桌邊等回答。", empathy: "你想維持合作，也知道一口答應後今晚可能又得留下來補自己的進度。", explain: "說明可支援的時間，是讓幫忙有邊界，不是拒絕合作。", action: "回覆一個選擇：現在看十分鐘、明早一起看，或推薦更合適的人。", reframe: "能安排的支援，才做得久也做得好。", singleCta: "支援窗", contentType: "職場界線" },
  { category: "女性成長", title: "工作成果被轉述時，先補上一句你的貢獻", hook: "會議裡大家都在講成果，卻沒人提到那一段其實是你整理的嗎？", scene: "簡報翻到成果頁，主管點頭，畫面上的名字卻只有專案名稱。", empathy: "你不想搶功，也怕一直不說，之後大家只記得事情自己完成了。", explain: "補充自己負責的具體段落，是讓協作紀錄完整，不是把功勞搶回來。", action: "接著說：這部分我把哪個問題整理成了什麼做法。", reframe: "把貢獻說清楚，團隊才能知道下次該找誰。", singleCta: "貢獻句", contentType: "專業定位" },
  { category: "女性成長", title: "想轉到新領域時，先挑一個能帶走的工作能力", hook: "想換跑道卻覺得以前經驗全都不算，你是不是越看職缺越沒底？", scene: "你開著新領域的職缺頁，游標停在『相關經驗』四個字。", empathy: "你很想前進，又怕自己沒有從零開始的勇氣和資格。", explain: "轉職不必否定過去，先找一項能在新場景解決問題的能力。", action: "從舊工作挑一件事，寫出你怎麼讓人、流程或結果變得更順。", reframe: "帶得走的能力，就是下一段職涯的起點。", singleCta: "帶走力", contentType: "職涯轉換" },
  { category: "女性成長", title: "客戶問能不能再便宜時，先把服務範圍攤開", hook: "客戶一句能不能算便宜，你是不是立刻開始懷疑自己開太高？", scene: "報價信剛寄出，對方回覆只寫了：預算有限，能調整嗎？", empathy: "你想接到合作，也怕一降價就把原本要做的事全吞進去。", explain: "價格討論前先對齊範圍，才能分辨是在調整內容還是在壓低你的投入。", action: "列出必做項目與可選項目，請對方先選想保留的部分。", reframe: "範圍清楚後，談的才是合作，不是自我消耗。", singleCta: "範圍單", contentType: "創業報價" },
  { category: "女性成長", title: "第一次帶新人時，先說明你會怎麼一起看進度", hook: "第一次帶新人，你怕管太多又怕放太鬆，結果每次都臨時救火嗎？", scene: "新人傳來完成檔案，你才發現方向和你想的不同。", empathy: "你希望他有空間，也不想把每個細節都扛回自己身上。", explain: "先約好回看節點，能把帶人從事後修正改成途中對齊。", action: "在開始時約兩次短回看：方向一次、交付前一次。", reframe: "有節點的信任，讓彼此都能放心前進。", singleCta: "回看點", contentType: "領導帶人" },
  { category: "女性成長", title: "跨部門意見打架時，先問這次要保住什麼", hook: "兩個部門各有道理，會議越開越久，你卻不知道怎麼讓大家往前嗎？", scene: "白板上寫滿不同需求，沒有人願意先拿掉自己那一條。", empathy: "你想公平聽每個人，也怕最後只剩更累的折衷方案。", explain: "把討論拉回共同要保住的結果，意見才有比較的基準。", action: "問全場：這次最不能犧牲的是速度、品質還是使用者感受？", reframe: "共同目標清楚，分歧才有一起處理的方法。", singleCta: "保住點", contentType: "跨部門協作" },
  { category: "女性成長", title: "準備談職稱時，先寫下你已經承接的角色", hook: "工作內容早就變了，職稱卻沒動，你是不是又怕提了很尷尬？", scene: "你整理年度工作，發現自己已經在協調原本不屬於職位的事情。", empathy: "你擔心開口像在要求頭銜，也知道名稱會影響別人怎麼找你合作。", explain: "職稱討論可以從實際角色開始，不必先把它說成一場要求。", action: "整理三件已穩定承接的責任，對照現職稱是否能說明它們。", reframe: "角色被說對，後續的期待才更容易對齊。", singleCta: "角色名", contentType: "職涯發展" },
  { category: "女性成長", title: "提案被說太理想時，先請對方指出卡住的條件", hook: "聽到這太理想了，你是不是立刻把整份提案收起來不敢再談？", scene: "提案講到一半，對方皺眉說：現實上可能做不到。", empathy: "你想守住想法，也怕硬撐讓對話變成誰比較有道理。", explain: "把『太理想』拆成具體限制，才能知道要改的是資源、時程還是目標。", action: "追問：你最擔心哪個條件現在無法成立？", reframe: "限制被說出來，創意才有可以落地的地方。", singleCta: "限制題", contentType: "提案溝通" },
  { category: "女性成長", title: "接手混亂專案時，先做一張誰找誰的地圖", hook: "一接手就有人丟來不同版本，你是不是連第一通電話該打給誰都不確定？", scene: "共用資料夾有五個資料夾名稱相近，訊息還在不停跳出。", empathy: "你想快點穩住局面，也怕先做錯判斷讓後面的人更難接。", explain: "先看清角色之間怎麼連，才能知道資訊該往哪裡收。", action: "畫出三欄：需求誰提、工作誰做、決定誰確認。", reframe: "先找到人與人的路徑，混亂就有整理的起點。", singleCta: "聯絡圖", contentType: "專案管理" },
  { category: "女性成長", title: "想申請內部機會時，先約一段探索對話", hook: "看到公司內部職缺很心動，卻怕一問就被當成要離開現在團隊嗎？", scene: "內網的招募公告停在螢幕上，你反覆看著聯絡人名字。", empathy: "你不想衝動表態，也不想因為猜測錯過了解工作的機會。", explain: "探索對話是蒐集工作樣貌，不等於立刻做出轉換承諾。", action: "約十五分鐘，問對方一週最常解決什麼問題。", reframe: "先認識真實工作，再決定要不要往前。", singleCta: "探索約", contentType: "職涯轉換" },
  { category: "金錢價值觀", title: "揪團送禮前，先決定你想參與到哪裡", hook: "群組忽然開始揪送禮，你怕沒跟上又不確定自己想花多少嗎？", scene: "同事群組一直跳出禮物連結，大家已開始接龍金額。", empathy: "你想表達心意，也不想在沒想過的狀態下跟著加碼。", explain: "參與心意有很多方式，不必只用同一個金額來證明。", action: "選一種：一起出一小份、寫卡片，或在適合時親自祝福。", reframe: "心意有選擇，關係不必靠勉強買單。", singleCta: "心意選", contentType: "人際金錢" },
  { category: "金錢價值觀", title: "外送費讓你猶豫時，先看你在買哪種方便", hook: "看到外送費就覺得不值，卻還是點了，你其實想換回什麼時間嗎？", scene: "晚餐時間到了，你盯著外送頁的費用和廚房裡還沒洗的鍋子。", empathy: "你想把錢花得值得，也知道今天的力氣可能真的不夠再做一餐。", explain: "把方便說清楚，才能分辨是臨時照顧自己還是習慣性滑下單。", action: "下單前選一句：我今天買的是時間、體力，還是不想想菜色。", reframe: "看見交換的東西，花費就不只剩罪惡感。", singleCta: "方便名", contentType: "日常消費" },
  { category: "金錢價值觀", title: "點數快到期時，先別讓它替你決定購物", hook: "點數快過期就急著湊單，你有沒有發現它正在幫你挑東西？", scene: "App 跳出最後一天通知，你開始翻原本不會看的商品分類。", empathy: "你不想浪費手上的點數，也怕為了用掉反而多花更多。", explain: "點數的期限是真實的，需求也要是真的，兩件事不必綁在一起。", action: "先看能否折抵原本會買的品項；沒有就讓它自然到期。", reframe: "不為了回收小額價值，製造更大的支出。", singleCta: "點數停", contentType: "優惠選擇" },
  { category: "金錢價值觀", title: "想退貨卻覺得麻煩時，先算進你會不會一直看見它", hook: "買回來才發現不適合，你是不是因為不好意思就把它塞進角落？", scene: "新買的衣服還掛著吊牌，衣櫃門一開你又看見它。", empathy: "你不想承認選錯，也覺得退貨流程會占掉不少時間。", explain: "留下不適合的東西也有成本，會占空間、注意力和下一次選擇。", action: "看退貨期限，今天只做一件事：印單、裝袋或查寄件點。", reframe: "修正一次購買，不需要把它變成長期負擔。", singleCta: "退貨步", contentType: "購物整理" },
  { category: "金錢價值觀", title: "續訂訂閱前，先想沒有它的那一週會怎樣", hook: "訂閱又自動續了，你才想起上個月根本沒打開幾次嗎？", scene: "扣款通知跳出時，你才從信箱搜尋上次使用服務的日期。", empathy: "你怕取消後需要時麻煩，也不想讓每個小額扣款默默累積。", explain: "想像少了它的一週，比只看價格更容易看見真正依賴。", action: "暫停一個月，記下哪一次真的覺得少了它。", reframe: "先讓使用感說話，續訂才是自己的選擇。", singleCta: "停用週", contentType: "訂閱管理" },
  { category: "金錢價值觀", title: "旅途中想買紀念品時，先選你想帶回哪個片段", hook: "旅行看到什麼都想買，回家後卻常想不起每件東西的故事嗎？", scene: "市集攤位一整排小物，你手上已拿了三樣還在挑。", empathy: "你想把旅程帶回家，也怕當下的熱鬧散了只剩收納壓力。", explain: "先選想記住的片段，紀念品才不需要用數量來承擔回憶。", action: "選一個場景：那頓飯、那條路或一起笑的時刻，再找一樣對應物。", reframe: "記得得夠清楚，一件東西也能裝下旅程。", singleCta: "旅程物", contentType: "旅行消費" },
  { category: "金錢價值觀", title: "看到限量色時，先問它會出現在哪一天", hook: "限量色一出你就怕錯過，但它真的會走進你的日常嗎？", scene: "品牌頁寫著限量發售，你把商品頁在購物車和收藏間來回切換。", empathy: "你喜歡它帶來的新鮮感，也怕錯過後一直覺得可惜。", explain: "把喜歡放進具體一天，能分辨收藏衝動和生活使用。", action: "說出三個會用它的場合；想不出來就先收藏七天。", reframe: "喜歡可以慢一點，仍會是你的喜歡。", singleCta: "日用想", contentType: "衝動消費" },
  { category: "金錢價值觀", title: "數位空間快滿時，先看你想保留的是什麼", hook: "雲端空間滿了就想加購，你有先看過裡面留著哪些檔案嗎？", scene: "手機跳出儲存空間不足，你直接被帶到升級方案頁面。", empathy: "你怕照片不見，也不想花時間逐一整理那些看起來都重要的檔案。", explain: "空間的價值在於保留你真的想回看的內容，不只是容量變大。", action: "先清一類：重複截圖、已下載檔案或模糊照片，再決定是否需要加購。", reframe: "先選擇留下什麼，空間才會更像自己的。", singleCta: "保留清", contentType: "數位消費" },
  { category: "金錢價值觀", title: "刷卡後心裡空空時，先回看今天最想逃開什麼", hook: "買完東西沒有更開心，你是不是又想用下一筆來補那個空？", scene: "包裹確認頁亮著，你關掉手機後卻還是坐在沙發上發呆。", empathy: "你想讓自己好過一點，也不希望每次累的時候只剩下買東西。", explain: "有些消費是在替情緒找出口，先看見當下的需要比責怪自己有用。", action: "寫一個空格：我現在比較需要休息、陪伴，還是把事情暫停。", reframe: "照顧需要不只一種方式，購物不必獨自扛這件事。", singleCta: "需要格", contentType: "情緒與消費" },
  { category: "金錢價值觀", title: "週末想清空錢包時，先找出三筆還記得的花費", hook: "覺得這週錢花得很快，你是不是只想趕快算出一個可怕總數？", scene: "週日晚上打開交易紀錄，密密麻麻的金額讓你立刻想關掉。", empathy: "你想弄清楚錢去哪裡，也怕一看就證明自己很不會控制。", explain: "先從記得的花費回看情境，比一次審判所有支出更容易開始。", action: "挑三筆，旁邊寫下當時在哪裡、和誰、為了什麼。", reframe: "理解花費的脈絡，比責備自己更能帶來選擇。", singleCta: "三筆看", contentType: "日常回看" },
  { category: "親子關係", title: "要離開遊戲場時，先讓孩子選最後一個收尾", hook: "每次要離開遊戲場就拉扯，你是不是一說回家就開始倒數生氣？", scene: "天色變暗了，孩子還在溜滑梯旁說再一次。", empathy: "你知道該回家，也不想每次結束都像把快樂硬切斷。", explain: "結束前有一個可預期的收尾，能讓轉換不只剩突然被帶走。", action: "讓他選最後一次溜滑梯、最後盪十下，或去和設施說再見。", reframe: "有告別的結束，也能好好往下一站走。", singleCta: "收尾選", contentType: "外出轉換" },
  { category: "親子關係", title: "早上挑衣服卡住時，先縮成兩件能出門的選項", hook: "孩子站在衣櫃前一直換，你看著時間卻越來越急嗎？", scene: "書包已背好，床上卻堆著三套剛被換下來的衣服。", empathy: "你想準時出門，也不想把一天開場變成誰贏誰輸。", explain: "選項太多時，先縮小範圍能讓決定有地方落下。", action: "拿兩件適合天氣的衣服，讓他選一件或指定一個配件。", reframe: "選擇被縮小，早晨仍能保留自己的聲音。", singleCta: "兩件選", contentType: "早晨流程" },
  { category: "親子關係", title: "孩子問同一題很多次時，先說你聽見他在擔心", hook: "孩子一直問等等真的會去嗎，你是不是越回答越想叫他不要再問？", scene: "鞋子都穿好了，他第三次抬頭問：我們真的要出發嗎？", empathy: "你想趕快出門，也怕自己不耐煩後他更需要一直確認。", explain: "重複提問有時是在找安心，不一定是沒有聽見答案。", action: "先說：你很想確定會去，我們穿好鞋就出發；再指給他看下一步。", reframe: "先接住想確認的心，回答才不必越來越大聲。", singleCta: "確認句", contentType: "日常安心" },
  { category: "親子關係", title: "手足搶同一樣東西時，先把兩個人的想法都說出來", hook: "兩個孩子同時抓住一個玩具，你是不是馬上只想判誰先拿到？", scene: "客廳中央一個玩具被兩雙手拉著，哭聲越來越高。", empathy: "你想快點停下衝突，也不想讓其中一個覺得自己的想法沒被看見。", explain: "先把各自想要的話說出來，才有機會一起找下一步。", action: "分別說：你還想玩、你也想現在輪到；再選計時、交換或找相似物。", reframe: "被聽見不保證立刻同意，但能讓協商有起點。", singleCta: "雙句說", contentType: "手足互動" },
  { category: "親子關係", title: "孩子寫到煩時，先讓他指出最不想碰的那一格", hook: "作業攤開就說好煩，你是不是一邊催一邊也不知道從哪裡幫？", scene: "鉛筆停在紙上，孩子把臉埋進手臂裡不看題目。", empathy: "你希望事情能完成，也不想把陪伴變成不停提醒。", explain: "先找到最卡的地方，才能把大份量縮成一個可處理的點。", action: "請他圈出最不想做的一格，選先一起讀題、先跳過或先做旁邊一題。", reframe: "卡住有位置後，前進不必一次解決全部。", singleCta: "卡格圈", contentType: "學習陪伴" },
  { category: "親子關係", title: "看影片時間到了時，先替下一件事準備接手", hook: "影片一關就不高興，你是不是每次都只能重複說時間到了？", scene: "倒數提示響了，孩子的眼睛還停在螢幕最後一幕。", empathy: "你想守住安排，也知道突然抽走喜歡的事會讓人很難轉身。", explain: "下一件事先有可接的內容，結束才不會只剩被拿走。", action: "關前先選下一步：拿水、播一首歌，或一起把角色畫下來。", reframe: "有地方可以去，離開螢幕不必只靠拉走。", singleCta: "接手事", contentType: "螢幕轉換" },
  { category: "親子關係", title: "弄丟心愛作品時，先陪他找最後看見的地方", hook: "孩子找不到剛畫好的圖就哭，你是不是也急著叫他不要哭了？", scene: "桌上只剩彩色筆，剛才完成的畫卻找不到了。", empathy: "你想快點找回來，也怕自己的著急讓他覺得作品不重要。", explain: "先一起回到最後看見的地方，是把焦急變成可以一起做的事。", action: "照順序走三站：桌上、書包、剛才坐的地方；每站停十秒找。", reframe: "作品被重視，不只在找到的那一刻。", singleCta: "三站找", contentType: "失落陪伴" },
  { category: "親子關係", title: "親友聚會不想打招呼時，先給孩子一個靠近方式", hook: "孩子看到親戚就躲在你後面，你是不是立刻替他說快叫人？", scene: "門一打開，大家笑著靠近，孩子抓緊你的衣角不說話。", empathy: "你想顧到禮貌，也不想讓他在一群目光裡更想退後。", explain: "靠近可以有不同速度，先有安全做法比立刻開口更重要。", action: "讓他選點頭、揮手、躲在你旁邊聽你先介紹，或晚點再說。", reframe: "保留靠近的方式，關係才有自己的節奏。", singleCta: "靠近法", contentType: "家庭聚會" },
  { category: "親子關係", title: "孩子說不想去活動時，先問他最不想面對哪一段", hook: "出門前突然說不想去，你是不是一邊趕時間一邊只想問為什麼？", scene: "外套已拿在手上，孩子坐在玄關邊說今天不想去了。", empathy: "你已經安排好行程，也不想忽略他此刻說不出口的抗拒。", explain: "把不想去拆成一段具體時刻，才知道是否有能調整的地方。", action: "問他比較不想要進門、和人說話，還是待到最後；一起選一個小調整。", reframe: "聽見哪一段難，行程仍可能有比較舒服的走法。", singleCta: "哪段難", contentType: "外出陪伴" },
  { category: "親子關係", title: "回家後一直黏著你時，先說清楚你何時能專心陪", hook: "一回家孩子就不停叫你，你還沒放下包包就覺得喘不過氣嗎？", scene: "鑰匙剛放桌上，孩子已拉著你要看剛做好的東西。", empathy: "你想好好回應，也需要幾分鐘把自己從外面的節奏切回來。", explain: "把等待時間說成可預期的約定，比含糊拖著更容易被理解。", action: "說：我先洗手喝水五分鐘，計時器響了就坐這裡看你的作品。", reframe: "照顧自己的轉換，也能讓陪伴更專心。", singleCta: "五分約", contentType: "返家連結" },
];

const formulaIndexes = new Map<string, number>();
export const dailyTopics20260824: Topic[] = drafts.map((draft, index) => {
  const { formula, formulaOrder } = formulaConfig[index % formulaConfig.length];
  const formulaIndex = (formulaIndexes.get(formula) ?? 0) + 1;
  formulaIndexes.set(formula, formulaIndex);
  const guardrail = guardrails[draft.category as Category];
  const thought = draft.hook.replace(/[，、。？！「」]/g, "");
  return { id: `D20260824-${String(index + 1).padStart(2, "0")}`, formula, formulaOrder, formulaIndex, category: draft.category, title: draft.title, hook: draft.hook, scene: draft.scene, angle: draft.explain, structure: "痛點開場 → 承接限制與情緒 → 白話拆解 → 一至三個低門檻選擇 → 轉念收尾 → 單一關鍵字 CTA", visual: `${draft.scene}畫面切到日常動作與一句關鍵文字，最後停在 CTA。`, cta: draft.singleCta, singleCta: draft.singleCta, risk: guardrail.risk, check: guardrail.check, series: `${draft.category}｜${formula}｜Keep 28 天影片語氣`, contentType: draft.contentType, empathy: draft.empathy, explain: draft.explain, action: draft.action, reframe: draft.reframe, storyline: `從「${draft.title}」的日常瞬間開始，承接「${draft.empathy}」，用「${draft.explain}」拆開卡點，給出「${draft.action}」，最後回到「${draft.reframe}」。`, storyElements: `場景：${draft.scene}｜心聲：${thought}｜行動：${draft.action}｜轉念：${draft.reframe}`, threeLayer: `痛點層：${draft.empathy}｜理解層：${draft.explain}｜選擇層：${draft.action}｜收束：${draft.reframe}` };
});
